apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    note: Hello,I am Development!
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: codisclusters.codis.k8s.io
spec:
  group: codis.k8s.io
  names:
    kind: CodisCluster
    plural: codisclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            codisDashboard:
              properties:
                productAuth:
                  type: string
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              - productAuth
              type: object
            codisFe:
              properties:
                replicas:
                  format: int32
                  type: integer
                serviceAnnotations:
                  type: object
                serviceType:
                  type: string
              required:
              - replicas
              - serviceType
              type: object
            codisProxy:
              properties:
                hpaSpec:
                  properties:
                    cpuUsedThreshold:
                      format: int32
                      type: integer
                    maxReplicas:
                      format: int32
                      type: integer
                    minReplicas:
                      format: int32
                      type: integer
                  required:
                  - minReplicas
                  - maxReplicas
                  - cpuUsedThreshold
                  type: object
                maxSurge:
                  format: int64
                  type: integer
                maxUnavailable:
                  format: int64
                  type: integer
                nodeSelector:
                  type: object
                replicas:
                  format: int32
                  type: integer
                serviceAnnotations:
                  type: object
                serviceType:
                  type: string
                sessionAuth:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              - sessionAuth
              - serviceType
              type: object
            codisServer:
              properties:
                groupReplicas:
                  format: int32
                  type: integer
                nodeSelector:
                  type: object
                partition:
                  format: int32
                  type: integer
                replicas:
                  format: int32
                  type: integer
                storageClassName:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              - groupReplicas
              type: object
            coordinatorAddr:
              type: string
            coordinatorName:
              type: string
            schedulerName:
              type: string
            sentinel:
              properties:
                nodeSelector:
                  type: object
                replicas:
                  format: int32
                  type: integer
                storageClassName:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              type: object
          required:
          - coordinatorName
          - coordinatorAddr
          type: object
        status:
          properties:
            codisDashboard:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            codisFeStatus:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisProxy:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisServer:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            sentinelStatus:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    note: Hello,I am Development!
  name: dev-default
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    note: Hello,I am Development!
  creationTimestamp: null
  name: dev-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - codis.k8s.io
  resources:
  - codisclusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    note: Hello,I am Development!
  creationTimestamp: null
  name: dev-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-manager-role
subjects:
- kind: ServiceAccount
  name: dev-default
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    note: Hello,I am Development!
  name: dev-webhook-server-secret
  namespace: system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello,I am Development!
  labels:
    control-plane: codis-operator
    controller-tools.k8s.io: "1.0"
  name: dev-codis-operator-service
  namespace: system
spec:
  ports:
  - port: 443
  selector:
    control-plane: codis-operator
    controller-tools.k8s.io: "1.0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    note: Hello,I am Development!
  labels:
    control-plane: codis-operator
    controller-tools.k8s.io: "1.0"
  name: dev-codis-operator
  namespace: system
spec:
  selector:
    matchLabels:
      control-plane: codis-operator
      controller-tools.k8s.io: "1.0"
  serviceName: dev-codis-operator-service
  template:
    metadata:
      annotations:
        note: Hello,I am Development!
      labels:
        control-plane: codis-operator
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /root/manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: dev-webhook-server-secret
        image: ccr.ccs.tencentyun.com/codis/codis-operator:latest
        imagePullPolicy: IfNotPresent
        name: codis-operator
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      serviceAccountName: dev-default
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: dev-webhook-server-secret
