apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: codisclusters.codis.k8s.io
spec:
  group: codis.k8s.io
  names:
    kind: CodisCluster
    plural: codisclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            codisDashboard:
              properties:
                productAuth:
                  type: string
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              - productAuth
              type: object
            codisFe:
              properties:
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              type: object
            codisProxy:
              properties:
                hpaSpec:
                  properties:
                    cpuUsedThreshold:
                      format: int32
                      type: integer
                    maxReplicas:
                      format: int32
                      type: integer
                    minReplicas:
                      format: int32
                      type: integer
                  required:
                  - minReplicas
                  - maxReplicas
                  - cpuUsedThreshold
                  type: object
                maxSurge:
                  format: int64
                  type: integer
                maxUnavailable:
                  format: int64
                  type: integer
                nodeSelector:
                  type: object
                replicas:
                  format: int32
                  type: integer
                sessionAuth:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              - sessionAuth
              type: object
            codisServer:
              properties:
                groupReplicas:
                  format: int32
                  type: integer
                nodeSelector:
                  type: object
                partition:
                  format: int32
                  type: integer
                replicas:
                  format: int32
                  type: integer
                storageClassName:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              - groupReplicas
              type: object
            coordinatorAddr:
              type: string
            coordinatorName:
              type: string
            schedulerName:
              type: string
            sentinel:
              properties:
                nodeSelector:
                  type: object
                replicas:
                  format: int32
                  type: integer
                storageClassName:
                  type: string
                tolerations:
                  items:
                    type: object
                  type: array
              required:
              - replicas
              type: object
          required:
          - coordinatorName
          - coordinatorAddr
          type: object
        status:
          properties:
            codisDashboard:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            codisFeStatus:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisProxy:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisServer:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            sentinelStatus:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
