apiVersion: codis.k8s.io/v1alpha1
kind: CodisCluster
metadata:
  labels:
    app: codis-cluster
  name: sample
spec:
  #coordinatorName: etcd
  #coordinatorName: zookeeper
  coordinatorName: filesystem
  coordinatorAddr: builtin
  codisProxy:
    replicas: 3
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
    sessionAuth: session
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 800Mi
    hpaSpec:
      minReplicas: 1
      maxReplicas: 5
      cpuUsedThreshold: 10
    maxSurge: 1
    maxUnavailable: 1
  codisServer:
    replicas: 4
    groupReplicas: 2
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
    partition: 0
  codisDashboard:
    replicas: 1
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
    productAuth: product
  codisFe:
    replicas: 2
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
  sentinel:
    replicas: 5
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
