apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codis-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: ccr.ccs.tencentyun.com/codis/codis-operator:latest
        name: codis-operator
        imagePullPolicy: IfNotPresent
